apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - argocd-crd.yaml
  - serviceaccount.yaml
  - serviceaccount-controller.yaml
  - configmap.yaml
  - argocd-rbac-cm.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - application-controller.yaml
  - clusterrole-server.yaml
  - clusterrolebinding-server.yaml
  - clusterrole-controller.yaml
  - clusterrolebinding-controller.yaml
  - repo-server-deployment.yaml
  - repo-server-service.yaml
  - argocd-dex-server-deployment.yaml
  - argocd-dex-server-service.yaml
  - argocd-dex-server-config.yaml
  - argocd-ingress.yaml
