apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-admin
  namespace: argocd
  labels:
    app.kubernetes.io/name: postgres-admin
    app.kubernetes.io/component: database-admin
spec:
  project: default
  source:
    repoURL: https://github.com/azhe403/homelab-k3d.git
    targetRevision: HEAD
    path: apps/postgres-admin/base
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
