apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flipt
  namespace: argocd
  labels:
    app.kubernetes.io/name: flipt
    app.kubernetes.io/component: feature-flags
spec:
  project: default
  source:
    repoURL: https://github.com/azhe403/homelab-k3d.git
    targetRevision: HEAD
    path: apps/flipt/overlays/v2
  destination:
    server: https://kubernetes.default.svc
    namespace: flipt-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
