apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31432
  type: NodePort
