apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: management
spec:
  project: applications
  source:
    repoURL: https://github.com/azhe403/homelab-k3d.git
    targetRevision: HEAD
    path: apps/rancher/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
