apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rancher
  namespace: cattle-system

resources:
  - 01-namespace.yaml
  - 02-serviceaccount.yaml
  - 03-rbac.yaml
  - 02-rancher-deployment.yaml
  - 03-rancher-service.yaml
  - 04-rancher-pvc.yaml
  - 05-rancher-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: rancher
      app.kubernetes.io/component: management
      app.kubernetes.io/managed-by: kustomize
