apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: default
data:
  cluster.ip: "10.101.39.236"
  cluster.name: "homelab"
  cluster.network: "k3d-homelab"
  loadbalancer.http.port: "80"
  loadbalancer.https.port: "443"
  loadbalancer.ports: "80,443,1-65535"
  nodeport.range: "1-65535"
