apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: default
data:
  cluster.ip: "10.101.39.236"
  cluster.name: "homelab"
  cluster.network: "k3d-homelab"
  loadbalancer.http.port: "80"
  loadbalancer.https.port: "443"
  loadbalancer.ports: "80,443,30000-30100"
  nodeport.range: "30000-30100"
  disable.traefik: "true"
  disable.servicelb: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config
  namespace: kube-system
data:
  ip.range: "10.101.39.236/24"
  network.name: "k3d-homelab"
  service.cluster.ip.range: "10.43.0.0/16"
  pod.cluster.ip.range: "10.42.0.0/16"
