apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-serviceaccount.yaml
  - 03-configmap.yaml
  - 04-vault-agent-config.yaml
  - 05-netbird-daemonset.yaml
