apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flipt-v1

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: flipt/flipt:latest
  target:
    kind: Deployment
    name: flipt
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: flipt-v1.azhe.my.id
    - op: replace
      path: /spec/rules/0/host
      value: flipt-v1.azhe.my.id
  target:
    kind: Ingress
    name: flipt-ingress
