apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-apps
    app.kubernetes.io/component: applications
spec:
  project: default
  source:
    repoURL: https://github.com/azhe403/homelab-k3d.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
