apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-infrastructure
    app.kubernetes.io/component: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/azhe403/homelab-k3d.git
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
