apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    storage "file" {
      path = "/vault/data"
    }
    
    api_addr = "http://vault-service.vault.svc.cluster.local:8200"
    cluster_addr = "http://vault-service.vault.svc.cluster.local:8201"
    
    disable_mlock = true
    
    log_level = "info"
