apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-namespace.yaml
- 02-vault-config.yaml
- 03-vault-pvc.yaml
- 04-vault-service.yaml
- 05-vault-deployment.yaml
- 06-vault-ingress.yaml
- 07-vault-init-job.yaml
- 08-vault-serviceaccount-rbac.yaml
