apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: vault
spec:
  type: NodePort
  ports:
    - name: vault-ui
      port: 8200
      targetPort: 8200
      protocol: TCP
      nodePort: 32000
    - name: vault-cluster
      port: 8201
      targetPort: 8201
      protocol: TCP
      nodePort: 32001
