apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
  labels:
    app.kubernetes.io/part-of: cloudflared
data:
  config.yaml: |
    tunnel: e60e7e9c-19f0-404b-809f-ce1fe0f3654f
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - hostname: argo.azhe.my.id
        service: http://argocd-server.argocd.svc.cluster.local:80

      - hostname: keycloak.azhe.my.id
        service: http://keycloak-service.keycloak.svc.cluster.local:8080

      - hostname: flipt.azhe.my.id
        service: http://flipt-service.flipt-v2.svc.cluster.local:8080

      - hostname: flipt-v1.azhe.my.id
        service: http://flipt-service.flipt-v2.svc.cluster.local:8080

      - hostname: hashi-vault.azhe.my.id
        service: http://vault-service.vault.svc.cluster.local:8200

      - hostname: rancher.azhe.my.id
        service: https://rancher.cattle-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pgadmin.azhe.my.id
        service: http://pgadmin-service.postgres-admin.svc.cluster.local:80

      - service: http_status:404

    tcp:
      - hostname: postgres-01.azhe.my.id
        service: tcp://postgres-service.postgres.svc.cluster.local:5432

    warp-routing:
      enabled: true
